name: Build Application
on: [workflow_dispatch]

jobs:
  build:
    name: Build Application
    strategy:
      fail-fast: false
      matrix:
        build:
          [
            { name: lilith_launcher, platform: linux/amd64, os: ubuntu-latest },
            { name: lilith_launcher, platform: windows/amd64, os: windows-latest },
            { name: lilith_launcher, platform: darwin/universal, os: macos-latest },
          ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: theMackabu/wails-build-action@main
        with:
          package: true
          go-version: '1.22'
          node-version: '20.x'
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
